<!-- <!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <title>High Risk Patients Report</title>
    <style>
        body {
            font-family: Arial, sans-serif;
        }

        h2 {
            text-align: center;
        }

        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 20px;
        }

        th,
        td {
            border: 1px solid #999;
            padding: 8px;
            text-align: left;
        }

        th {
            background-color: #f2f2f2;
        }
    </style>
</head>

<body>
    <h2>High Risk Patients Report</h2>
    <table>
        <thead>
            <tr>
                <th>Full Name</th>
                <th>Email</th>
                <th>Chronic Conditions</th>
                <th>Medications</th>
                <th>Risk Score</th>
            </tr>
        </thead>
        <tbody>
            @foreach ($highRiskPatients as $profile)
                <tr>
                    <td>{{ $profile->full_name }}</td>
                    <td>{{ $profile->user->email }}</td>
                    <td>{{ implode(', ', $profile->chronic_conditions) }}</td>
                    <td>{{ implode(', ', $profile->medications) }}</td>
                    <td>{{ $profile->calculateRiskScore() }}</td>
                </tr>
            @endforeach
        </tbody>
    </table>
</body>

</html> -->

<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <title>High Risk Patients Report</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            font-size: 12px;
        }

        .header {
            text-align: center;
            margin-bottom: 20px;
        }

        .footer {
            margin-top: 20px;
            font-size: 10px;
            text-align: center;
        }

        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 10px;
        }

        th,
        td {
            border: 1px solid #ddd;
            padding: 6px;
            text-align: left;
        }

        th {
            background-color: #f2f2f2;
            font-weight: bold;
        }

        .risk-high {
            background-color: #ffe6e6;
        }
    </style>
</head>

<body>
    <div class="header">
        <h2>High Risk Patients Report</h2>
        <p>Generated on: {{ $reportDate }}</p>
        <p>Total High-Risk Patients: {{ count($highRiskPatients) }}</p>
    </div>

    <table>
        <thead>
            <tr>

                <th>Full Name</th>
                <th>Email</th>
                <th>Chronic Conditions</th>
                <th>Medications</th>
                <th>Risk Score</th>
            </tr>
        </thead>
        <tbody>
            @foreach ($highRiskPatients as $index => $profile)
                <tr class="{{ $profile->calculateRiskScore() > 9 ? 'risk-high' : '' }}">

                    <td>{{ $profile->full_name ?? 'N/A' }}</td>
                    <td>{{ $profile->user->email ?? 'N/A' }}</td>
                    <td>{{ $profile->chronic_conditions ? implode(', ', $profile->chronic_conditions) : 'None' }}</td>
                    <td>{{ $profile->medications ? implode(', ', $profile->medications) : 'None' }}</td>
                    <td>{{ $profile->calculateRiskScore() }}</td>
                </tr>
            @endforeach
        </tbody>
    </table>

    <div class="footer">
        <p>Report generated by MEDSITE Analytics Systems.</p>
    </div>
</body>

</html>